title: Jean Paul Nazon  # your name (or website title) here
logo: "/images/IMG-20210412-WA0010.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  Passionate about analytics, Statistics, machine learning, Neutral-Networks...
  <br><br>
  <a href="https://www.linkedin.com/in/jean-paul-nazon-b829b252/</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
